/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory, } from "@stencil/router";
export namespace Components {
    interface BlogComponent {
    }
    interface CoreRoot {
    }
    interface FooterComponent {
    }
    interface HomeComponent {
    }
    interface NavBar {
    }
    interface ProjectComponent {
    }
    interface RootRedirect {
        "history": RouterHistory;
    }
    interface TalkComponent {
    }
}
declare global {
    interface HTMLBlogComponentElement extends Components.BlogComponent, HTMLStencilElement {
    }
    var HTMLBlogComponentElement: {
        prototype: HTMLBlogComponentElement;
        new (): HTMLBlogComponentElement;
    };
    interface HTMLCoreRootElement extends Components.CoreRoot, HTMLStencilElement {
    }
    var HTMLCoreRootElement: {
        prototype: HTMLCoreRootElement;
        new (): HTMLCoreRootElement;
    };
    interface HTMLFooterComponentElement extends Components.FooterComponent, HTMLStencilElement {
    }
    var HTMLFooterComponentElement: {
        prototype: HTMLFooterComponentElement;
        new (): HTMLFooterComponentElement;
    };
    interface HTMLHomeComponentElement extends Components.HomeComponent, HTMLStencilElement {
    }
    var HTMLHomeComponentElement: {
        prototype: HTMLHomeComponentElement;
        new (): HTMLHomeComponentElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLProjectComponentElement extends Components.ProjectComponent, HTMLStencilElement {
    }
    var HTMLProjectComponentElement: {
        prototype: HTMLProjectComponentElement;
        new (): HTMLProjectComponentElement;
    };
    interface HTMLRootRedirectElement extends Components.RootRedirect, HTMLStencilElement {
    }
    var HTMLRootRedirectElement: {
        prototype: HTMLRootRedirectElement;
        new (): HTMLRootRedirectElement;
    };
    interface HTMLTalkComponentElement extends Components.TalkComponent, HTMLStencilElement {
    }
    var HTMLTalkComponentElement: {
        prototype: HTMLTalkComponentElement;
        new (): HTMLTalkComponentElement;
    };
    interface HTMLElementTagNameMap {
        "blog-component": HTMLBlogComponentElement;
        "core-root": HTMLCoreRootElement;
        "footer-component": HTMLFooterComponentElement;
        "home-component": HTMLHomeComponentElement;
        "nav-bar": HTMLNavBarElement;
        "project-component": HTMLProjectComponentElement;
        "root-redirect": HTMLRootRedirectElement;
        "talk-component": HTMLTalkComponentElement;
    }
}
declare namespace LocalJSX {
    interface BlogComponent {
    }
    interface CoreRoot {
    }
    interface FooterComponent {
    }
    interface HomeComponent {
    }
    interface NavBar {
    }
    interface ProjectComponent {
    }
    interface RootRedirect {
        "history"?: RouterHistory;
    }
    interface TalkComponent {
    }
    interface IntrinsicElements {
        "blog-component": BlogComponent;
        "core-root": CoreRoot;
        "footer-component": FooterComponent;
        "home-component": HomeComponent;
        "nav-bar": NavBar;
        "project-component": ProjectComponent;
        "root-redirect": RootRedirect;
        "talk-component": TalkComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blog-component": LocalJSX.BlogComponent & JSXBase.HTMLAttributes<HTMLBlogComponentElement>;
            "core-root": LocalJSX.CoreRoot & JSXBase.HTMLAttributes<HTMLCoreRootElement>;
            "footer-component": LocalJSX.FooterComponent & JSXBase.HTMLAttributes<HTMLFooterComponentElement>;
            "home-component": LocalJSX.HomeComponent & JSXBase.HTMLAttributes<HTMLHomeComponentElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "project-component": LocalJSX.ProjectComponent & JSXBase.HTMLAttributes<HTMLProjectComponentElement>;
            "root-redirect": LocalJSX.RootRedirect & JSXBase.HTMLAttributes<HTMLRootRedirectElement>;
            "talk-component": LocalJSX.TalkComponent & JSXBase.HTMLAttributes<HTMLTalkComponentElement>;
        }
    }
}
