/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory, } from "@stencil/router";
export namespace Components {
    interface BlogComponent {
    }
    interface CoreRoot {
    }
    interface FooterComponent {
    }
    interface HomeComponent {
    }
    interface NavBar {
    }
    interface ProjectComponent {
    }
    interface RootRedirect {
        "history": RouterHistory;
    }
    interface TalkComponent {
    }
    interface V2Experience {
    }
    interface V2Hero {
    }
    interface V2Home {
    }
    interface V2Nav {
    }
    interface V2Work {
    }
}
declare global {
    interface HTMLBlogComponentElement extends Components.BlogComponent, HTMLStencilElement {
    }
    var HTMLBlogComponentElement: {
        prototype: HTMLBlogComponentElement;
        new (): HTMLBlogComponentElement;
    };
    interface HTMLCoreRootElement extends Components.CoreRoot, HTMLStencilElement {
    }
    var HTMLCoreRootElement: {
        prototype: HTMLCoreRootElement;
        new (): HTMLCoreRootElement;
    };
    interface HTMLFooterComponentElement extends Components.FooterComponent, HTMLStencilElement {
    }
    var HTMLFooterComponentElement: {
        prototype: HTMLFooterComponentElement;
        new (): HTMLFooterComponentElement;
    };
    interface HTMLHomeComponentElement extends Components.HomeComponent, HTMLStencilElement {
    }
    var HTMLHomeComponentElement: {
        prototype: HTMLHomeComponentElement;
        new (): HTMLHomeComponentElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLProjectComponentElement extends Components.ProjectComponent, HTMLStencilElement {
    }
    var HTMLProjectComponentElement: {
        prototype: HTMLProjectComponentElement;
        new (): HTMLProjectComponentElement;
    };
    interface HTMLRootRedirectElement extends Components.RootRedirect, HTMLStencilElement {
    }
    var HTMLRootRedirectElement: {
        prototype: HTMLRootRedirectElement;
        new (): HTMLRootRedirectElement;
    };
    interface HTMLTalkComponentElement extends Components.TalkComponent, HTMLStencilElement {
    }
    var HTMLTalkComponentElement: {
        prototype: HTMLTalkComponentElement;
        new (): HTMLTalkComponentElement;
    };
    interface HTMLV2ExperienceElement extends Components.V2Experience, HTMLStencilElement {
    }
    var HTMLV2ExperienceElement: {
        prototype: HTMLV2ExperienceElement;
        new (): HTMLV2ExperienceElement;
    };
    interface HTMLV2HeroElement extends Components.V2Hero, HTMLStencilElement {
    }
    var HTMLV2HeroElement: {
        prototype: HTMLV2HeroElement;
        new (): HTMLV2HeroElement;
    };
    interface HTMLV2HomeElement extends Components.V2Home, HTMLStencilElement {
    }
    var HTMLV2HomeElement: {
        prototype: HTMLV2HomeElement;
        new (): HTMLV2HomeElement;
    };
    interface HTMLV2NavElement extends Components.V2Nav, HTMLStencilElement {
    }
    var HTMLV2NavElement: {
        prototype: HTMLV2NavElement;
        new (): HTMLV2NavElement;
    };
    interface HTMLV2WorkElement extends Components.V2Work, HTMLStencilElement {
    }
    var HTMLV2WorkElement: {
        prototype: HTMLV2WorkElement;
        new (): HTMLV2WorkElement;
    };
    interface HTMLElementTagNameMap {
        "blog-component": HTMLBlogComponentElement;
        "core-root": HTMLCoreRootElement;
        "footer-component": HTMLFooterComponentElement;
        "home-component": HTMLHomeComponentElement;
        "nav-bar": HTMLNavBarElement;
        "project-component": HTMLProjectComponentElement;
        "root-redirect": HTMLRootRedirectElement;
        "talk-component": HTMLTalkComponentElement;
        "v2-experience": HTMLV2ExperienceElement;
        "v2-hero": HTMLV2HeroElement;
        "v2-home": HTMLV2HomeElement;
        "v2-nav": HTMLV2NavElement;
        "v2-work": HTMLV2WorkElement;
    }
}
declare namespace LocalJSX {
    interface BlogComponent {
    }
    interface CoreRoot {
    }
    interface FooterComponent {
    }
    interface HomeComponent {
    }
    interface NavBar {
    }
    interface ProjectComponent {
    }
    interface RootRedirect {
        "history"?: RouterHistory;
    }
    interface TalkComponent {
    }
    interface V2Experience {
    }
    interface V2Hero {
    }
    interface V2Home {
    }
    interface V2Nav {
    }
    interface V2Work {
    }
    interface IntrinsicElements {
        "blog-component": BlogComponent;
        "core-root": CoreRoot;
        "footer-component": FooterComponent;
        "home-component": HomeComponent;
        "nav-bar": NavBar;
        "project-component": ProjectComponent;
        "root-redirect": RootRedirect;
        "talk-component": TalkComponent;
        "v2-experience": V2Experience;
        "v2-hero": V2Hero;
        "v2-home": V2Home;
        "v2-nav": V2Nav;
        "v2-work": V2Work;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blog-component": LocalJSX.BlogComponent & JSXBase.HTMLAttributes<HTMLBlogComponentElement>;
            "core-root": LocalJSX.CoreRoot & JSXBase.HTMLAttributes<HTMLCoreRootElement>;
            "footer-component": LocalJSX.FooterComponent & JSXBase.HTMLAttributes<HTMLFooterComponentElement>;
            "home-component": LocalJSX.HomeComponent & JSXBase.HTMLAttributes<HTMLHomeComponentElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "project-component": LocalJSX.ProjectComponent & JSXBase.HTMLAttributes<HTMLProjectComponentElement>;
            "root-redirect": LocalJSX.RootRedirect & JSXBase.HTMLAttributes<HTMLRootRedirectElement>;
            "talk-component": LocalJSX.TalkComponent & JSXBase.HTMLAttributes<HTMLTalkComponentElement>;
            "v2-experience": LocalJSX.V2Experience & JSXBase.HTMLAttributes<HTMLV2ExperienceElement>;
            "v2-hero": LocalJSX.V2Hero & JSXBase.HTMLAttributes<HTMLV2HeroElement>;
            "v2-home": LocalJSX.V2Home & JSXBase.HTMLAttributes<HTMLV2HomeElement>;
            "v2-nav": LocalJSX.V2Nav & JSXBase.HTMLAttributes<HTMLV2NavElement>;
            "v2-work": LocalJSX.V2Work & JSXBase.HTMLAttributes<HTMLV2WorkElement>;
        }
    }
}
