/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory, } from "@stencil/router";
export namespace Components {
    interface CoreRoot {
    }
    interface RootRedirect {
        "history": RouterHistory;
    }
    interface V2Experience {
    }
    interface V2Footer {
    }
    interface V2Future {
    }
    interface V2Hero {
    }
    interface V2Home {
    }
    interface V2Nav {
    }
    interface V2Projects {
    }
    interface V2Work {
    }
}
declare global {
    interface HTMLCoreRootElement extends Components.CoreRoot, HTMLStencilElement {
    }
    var HTMLCoreRootElement: {
        prototype: HTMLCoreRootElement;
        new (): HTMLCoreRootElement;
    };
    interface HTMLRootRedirectElement extends Components.RootRedirect, HTMLStencilElement {
    }
    var HTMLRootRedirectElement: {
        prototype: HTMLRootRedirectElement;
        new (): HTMLRootRedirectElement;
    };
    interface HTMLV2ExperienceElement extends Components.V2Experience, HTMLStencilElement {
    }
    var HTMLV2ExperienceElement: {
        prototype: HTMLV2ExperienceElement;
        new (): HTMLV2ExperienceElement;
    };
    interface HTMLV2FooterElement extends Components.V2Footer, HTMLStencilElement {
    }
    var HTMLV2FooterElement: {
        prototype: HTMLV2FooterElement;
        new (): HTMLV2FooterElement;
    };
    interface HTMLV2FutureElement extends Components.V2Future, HTMLStencilElement {
    }
    var HTMLV2FutureElement: {
        prototype: HTMLV2FutureElement;
        new (): HTMLV2FutureElement;
    };
    interface HTMLV2HeroElement extends Components.V2Hero, HTMLStencilElement {
    }
    var HTMLV2HeroElement: {
        prototype: HTMLV2HeroElement;
        new (): HTMLV2HeroElement;
    };
    interface HTMLV2HomeElement extends Components.V2Home, HTMLStencilElement {
    }
    var HTMLV2HomeElement: {
        prototype: HTMLV2HomeElement;
        new (): HTMLV2HomeElement;
    };
    interface HTMLV2NavElement extends Components.V2Nav, HTMLStencilElement {
    }
    var HTMLV2NavElement: {
        prototype: HTMLV2NavElement;
        new (): HTMLV2NavElement;
    };
    interface HTMLV2ProjectsElement extends Components.V2Projects, HTMLStencilElement {
    }
    var HTMLV2ProjectsElement: {
        prototype: HTMLV2ProjectsElement;
        new (): HTMLV2ProjectsElement;
    };
    interface HTMLV2WorkElement extends Components.V2Work, HTMLStencilElement {
    }
    var HTMLV2WorkElement: {
        prototype: HTMLV2WorkElement;
        new (): HTMLV2WorkElement;
    };
    interface HTMLElementTagNameMap {
        "core-root": HTMLCoreRootElement;
        "root-redirect": HTMLRootRedirectElement;
        "v2-experience": HTMLV2ExperienceElement;
        "v2-footer": HTMLV2FooterElement;
        "v2-future": HTMLV2FutureElement;
        "v2-hero": HTMLV2HeroElement;
        "v2-home": HTMLV2HomeElement;
        "v2-nav": HTMLV2NavElement;
        "v2-projects": HTMLV2ProjectsElement;
        "v2-work": HTMLV2WorkElement;
    }
}
declare namespace LocalJSX {
    interface CoreRoot {
    }
    interface RootRedirect {
        "history"?: RouterHistory;
    }
    interface V2Experience {
    }
    interface V2Footer {
    }
    interface V2Future {
    }
    interface V2Hero {
    }
    interface V2Home {
    }
    interface V2Nav {
    }
    interface V2Projects {
    }
    interface V2Work {
    }
    interface IntrinsicElements {
        "core-root": CoreRoot;
        "root-redirect": RootRedirect;
        "v2-experience": V2Experience;
        "v2-footer": V2Footer;
        "v2-future": V2Future;
        "v2-hero": V2Hero;
        "v2-home": V2Home;
        "v2-nav": V2Nav;
        "v2-projects": V2Projects;
        "v2-work": V2Work;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "core-root": LocalJSX.CoreRoot & JSXBase.HTMLAttributes<HTMLCoreRootElement>;
            "root-redirect": LocalJSX.RootRedirect & JSXBase.HTMLAttributes<HTMLRootRedirectElement>;
            "v2-experience": LocalJSX.V2Experience & JSXBase.HTMLAttributes<HTMLV2ExperienceElement>;
            "v2-footer": LocalJSX.V2Footer & JSXBase.HTMLAttributes<HTMLV2FooterElement>;
            "v2-future": LocalJSX.V2Future & JSXBase.HTMLAttributes<HTMLV2FutureElement>;
            "v2-hero": LocalJSX.V2Hero & JSXBase.HTMLAttributes<HTMLV2HeroElement>;
            "v2-home": LocalJSX.V2Home & JSXBase.HTMLAttributes<HTMLV2HomeElement>;
            "v2-nav": LocalJSX.V2Nav & JSXBase.HTMLAttributes<HTMLV2NavElement>;
            "v2-projects": LocalJSX.V2Projects & JSXBase.HTMLAttributes<HTMLV2ProjectsElement>;
            "v2-work": LocalJSX.V2Work & JSXBase.HTMLAttributes<HTMLV2WorkElement>;
        }
    }
}
